// Dữ liệu CHÍNH THỨC 48 đội bóng và 12 bảng đấu World Cup 2026 (Có bổ sung flagCode phục vụ hiển thị ảnh lá cờ)
const WORLD_CUP_DATA = {
  groups: {
    A: [
      { id: "MEX", name: "Mexico", code: "MEX", flagCode: "mx", flag: "🇲🇽" },
      { id: "KOR", name: "Hàn Quốc", code: "KOR", flagCode: "kr", flag: "🇰🇷" },
      { id: "RSA", name: "Nam Phi", code: "RSA", flagCode: "za", flag: "🇿🇦" },
      { id: "CZE", name: "Cộng hòa Séc", code: "CZE", flagCode: "cz", flag: "🇨🇿" }
    ],
    B: [
      { id: "CAN", name: "Canada", code: "CAN", flagCode: "ca", flag: "🇨🇦" },
      { id: "SUI", name: "Thụy Sĩ", code: "SUI", flagCode: "ch", flag: "🇨🇭" },
      { id: "QAT", name: "Qatar", code: "QAT", flagCode: "qa", flag: "🇶🇦" },
      { id: "BIH", name: "Bosnia-Herzegovina", code: "BIH", flagCode: "ba", flag: "🇧🇦" }
    ],
    C: [
      { id: "BRA", name: "Brazil", code: "BRA", flagCode: "br", flag: "🇧🇷" },
      { id: "MAR", name: "Morocco", code: "MAR", flagCode: "ma", flag: "🇲🇦" },
      { id: "SCO", name: "Scotland", code: "SCO", flagCode: "gb-sct", flag: "🏴" },
      { id: "HAI", name: "Haiti", code: "HAI", flagCode: "ht", flag: "🇭🇹" }
    ],
    D: [
      { id: "USA", name: "Mỹ", code: "USA", flagCode: "us", flag: "🇺🇸" },
      { id: "PAR", name: "Paraguay", code: "PAR", flagCode: "py", flag: "🇵🇾" },
      { id: "AUS", name: "Úc", code: "AUS", flagCode: "au", flag: "🇦🇺" },
      { id: "TUR", name: "Thổ Nhĩ Kỳ", code: "TUR", flagCode: "tr", flag: "🇹🇷" }
    ],
    E: [
      { id: "GER", name: "Đức", code: "GER", flagCode: "de", flag: "🇩🇪" },
      { id: "ECU", name: "Ecuador", code: "ECU", flagCode: "ec", flag: "🇪🇨" },
      { id: "CIV", name: "Bờ Biển Ngà", code: "CIV", flagCode: "ci", flag: "🇨🇮" },
      { id: "CUW", name: "Curacao", code: "CUW", flagCode: "cw", flag: "🇨🇼" }
    ],
    F: [
      { id: "NED", name: "Hà Lan", code: "NED", flagCode: "nl", flag: "🇳🇱" },
      { id: "JPN", name: "Nhật Bản", code: "JPN", flagCode: "jp", flag: "🇯🇵" },
      { id: "TUN", name: "Tunisia", code: "TUN", flagCode: "tn", flag: "🇹🇳" },
      { id: "SWE", name: "Thụy Điển", code: "SWE", flagCode: "se", flag: "🇸🇪" }
    ],
    G: [
      { id: "BEL", name: "Bỉ", code: "BEL", flagCode: "be", flag: "🇧🇪" },
      { id: "IRN", name: "Iran", code: "IRN", flagCode: "ir", flag: "🇮🇷" },
      { id: "EGY", name: "Ai Cập", code: "EGY", flagCode: "eg", flag: "🇪🇬" },
      { id: "NZL", name: "New Zealand", code: "NZL", flagCode: "nz", flag: "🇳🇿" }
    ],
    H: [
      { id: "ESP", name: "Tây Ban Nha", code: "ESP", flagCode: "es", flag: "🇪🇸" },
      { id: "URU", name: "Uruguay", code: "URU", flagCode: "uy", flag: "🇺🇾" },
      { id: "KSA", name: "Saudi Arabia", code: "KSA", flagCode: "sa", flag: "🇸🇦" },
      { id: "CPV", name: "Cape Verde", code: "CPV", flagCode: "cv", flag: "🇨🇻" }
    ],
    I: [
      { id: "FRA", name: "Pháp", code: "FRA", flagCode: "fr", flag: "🇫🇷" },
      { id: "SEN", name: "Senegal", code: "SEN", flagCode: "sn", flag: "🇸🇳" },
      { id: "NOR", name: "Na Uy", code: "NOR", flagCode: "no", flag: "🇳🇴" },
      { id: "IRQ", name: "Iraq", code: "IRQ", flagCode: "iq", flag: "🇮🇶" }
    ],
    J: [
      { id: "ARG", name: "Argentina", code: "ARG", flagCode: "ar", flag: "🇦🇷" },
      { id: "AUT", name: "Áo", code: "AUT", flagCode: "at", flag: "🇦🇹" },
      { id: "ALG", name: "Algeria", code: "ALG", flagCode: "dz", flag: "🇩🇿" },
      { id: "JOR", name: "Jordan", code: "JOR", flagCode: "jo", flag: "🇯🇴" }
    ],
    K: [
      { id: "POR", name: "Bồ Đào Nha", code: "POR", flagCode: "pt", flag: "🇵🇹" },
      { id: "COL", name: "Colombia", code: "COL", flagCode: "co", flag: "🇨🇴" },
      { id: "UZB", name: "Uzbekistan", code: "UZB", flagCode: "uz", flag: "🇺🇿" },
      { id: "COD", name: "CH Dân Chủ Congo", code: "COD", flagCode: "cd", flag: "🇨🇩" }
    ],
    L: [
      { id: "ENG", name: "Anh", code: "ENG", flagCode: "gb-eng", flag: "🏴" },
      { id: "CRO", name: "Croatia", code: "CRO", flagCode: "hr", flag: "🇭🇷" },
      { id: "PAN", name: "Panama", code: "PAN", flagCode: "pa", flag: "🇵🇦" },
      { id: "GHA", name: "Ghana", code: "GHA", flagCode: "gh", flag: "🇬🇭" }
    ]
  }
};

// Dá»¯ liá»‡u lá»‹ch thi Ä‘áº¥u chÃ­nh thá»©c vÃ²ng báº£ng World Cup 2026 tá»« ESPN API (72 tráº­n Ä‘áº¥u)
const OFFICIAL_MATCHES_RAW = [
  {
    id: "M01",
    group: "A",
    round: 1,
    date: "12/06/2026",
    timestamp: 1781204400000,
    time: "02:00",
    team1Id: "MEX",
    team2Id: "RSA",
    score1: 2,
    score2: 0,
    yc1: 1,
    rc1: 1,
    yc2: 2,
    rc2: 2,
    status: "Kết thúc",
    scorers1: [{ name: "Julián Quiñones", min: "9'" }, { name: "Raúl Jiménez", min: "67'" }],
    scorers2: [],
    matchTime: ""
  },
  {
    id: "M02",
    group: "A",
    round: 1,
    date: "12/06/2026",
    timestamp: 1781229600000,
    time: "09:00",
    team1Id: "KOR",
    team2Id: "CZE",
    score1: 2,
    score2: 1,
    yc1: 1,
    rc1: 0,
    yc2: 0,
    rc2: 0,
    status: "Kết thúc",
    scorers1: [{ name: "Hwang In-Beom", min: "67'" }, { name: "Oh Hyeon-Gyu", min: "80'" }],
    scorers2: [{ name: "Ladislav Krejcí", min: "59'" }],
    matchTime: ""
  },
  {
    id: "M03",
    group: "B",
    round: 1,
    date: "13/06/2026",
    timestamp: 1781290800000,
    time: "02:00",
    team1Id: "CAN",
    team2Id: "BIH",
    score1: 1,
    score2: 1,
    yc1: 2,
    rc1: 0,
    yc2: 3,
    rc2: 0,
    status: "Kết thúc",
    scorers1: [{ name: "Cyle Larin", min: "78'" }],
    scorers2: [{ name: "Jovo Lukic", min: "21'" }],
    matchTime: ""
  },
  {
    id: "M04",
    group: "D",
    round: 1,
    date: "13/06/2026",
    timestamp: 1781312400000,
    time: "08:00",
    team1Id: "USA",
    team2Id: "PAR",
    score1: 4,
    score2: 1,
    yc1: 1,
    rc1: 0,
    yc2: 5,
    rc2: 0,
    status: "Kết thúc",
    scorers1: [{ name: "Damián Bobadilla (OG)", min: "7'" }, { name: "Folarin Balogun", min: "31'" }, { name: "Folarin Balogun", min: "45'+5'" }, { name: "Giovanni Reyna", min: "90'+8'" }],
    scorers2: [{ name: "Maurício", min: "73'" }],
    matchTime: ""
  },
  {
    id: "M05",
    group: "B",
    round: 1,
    date: "14/06/2026",
    timestamp: 1781377200000,
    time: "02:00",
    team1Id: "QAT",
    team2Id: "SUI",
    score1: 1,
    score2: 1,
    yc1: 2,
    rc1: 0,
    yc2: 1,
    rc2: 0,
    status: "Kết thúc",
    scorers1: [{ name: "Miro Muheim (OG)", min: "90'+4'" }],
    scorers2: [{ name: "Breel Embolo", min: "17'" }],
    matchTime: ""
  },
  {
    id: "M06",
    group: "C",
    round: 1,
    date: "14/06/2026",
    timestamp: 1781388000000,
    time: "05:00",
    team1Id: "BRA",
    team2Id: "MAR",
    score1: 1,
    score2: 1,
    yc1: 2,
    rc1: 0,
    yc2: 0,
    rc2: 0,
    status: "Kết thúc",
    scorers1: [{ name: "Vinícius Júnior", min: "32'" }],
    scorers2: [{ name: "Ismael Saibari", min: "21'" }],
    matchTime: ""
  },
  {
    id: "M07",
    group: "C",
    round: 1,
    date: "14/06/2026",
    timestamp: 1781398800000,
    time: "08:00",
    team1Id: "HAI",
    team2Id: "SCO",
    score1: 0,
    score2: 1,
    yc1: 1,
    rc1: 0,
    yc2: 3,
    rc2: 0,
    status: "Kết thúc",
    scorers1: [],
    scorers2: [{ name: "John McGinn", min: "28'" }],
    matchTime: ""
  },
  {
    id: "M08",
    group: "D",
    round: 1,
    date: "14/06/2026",
    timestamp: 1781409600000,
    time: "11:00",
    team1Id: "AUS",
    team2Id: "TUR",
    score1: 2,
    score2: 0,
    yc1: 0,
    rc1: 0,
    yc2: 1,
    rc2: 0,
    status: "Kết thúc",
    scorers1: [{ name: "Nestory Irankunda", min: "27'" }, { name: "Connor Metcalfe", min: "75'" }],
    scorers2: [],
    matchTime: ""
  },
  {
    id: "M09",
    group: "E",
    round: 1,
    date: "15/06/2026",
    timestamp: 1781456400000,
    time: "00:00",
    team1Id: "GER",
    team2Id: "CUW",
    score1: 7,
    score2: 1,
    yc1: 0,
    rc1: 0,
    yc2: 0,
    rc2: 0,
    status: "Kết thúc",
    scorers1: [{ name: "Felix Nmecha", min: "6'" }, { name: "Nico Schlotterbeck", min: "38'" }, { name: "Kai Havertz", min: "45'+5'" }, { name: "Jamal Musiala", min: "47'" }, { name: "Nathaniel Brown", min: "68'" }, { name: "Deniz Undav", min: "78'" }, { name: "Kai Havertz", min: "88'" }],
    scorers2: [{ name: "Livano Comenencia", min: "21'" }],
    matchTime: ""
  },
  {
    id: "M10",
    group: "F",
    round: 1,
    date: "15/06/2026",
    timestamp: 1781467200000,
    time: "03:00",
    team1Id: "NED",
    team2Id: "JPN",
    score1: 2,
    score2: 2,
    yc1: 3,
    rc1: 0,
    yc2: 0,
    rc2: 0,
    status: "Kết thúc",
    scorers1: [{ name: "Virgil van Dijk", min: "51'" }, { name: "Crysencio Summerville", min: "64'" }],
    scorers2: [{ name: "Keito Nakamura", min: "57'" }, { name: "Daichi Kamada", min: "89'" }],
    matchTime: ""
  },
  {
    id: "M11",
    group: "E",
    round: 1,
    date: "15/06/2026",
    timestamp: 1781478000000,
    time: "06:00",
    team1Id: "CIV",
    team2Id: "ECU",
    score1: 0,
    score2: 0,
    yc1: 3,
    rc1: 0,
    yc2: 1,
    rc2: 0,
    status: "Đang đá",
    scorers1: [],
    scorers2: [],
    matchTime: ""
  },
  {
    id: "M12",
    group: "F",
    round: 1,
    date: "15/06/2026",
    timestamp: 1781488800000,
    time: "09:00",
    team1Id: "SWE",
    team2Id: "TUN",
    score1: null,
    score2: null,
    yc1: 0,
    rc1: 0,
    yc2: 0,
    rc2: 0,
    status: "Chưa đấu",
    scorers1: [],
    scorers2: [],
    matchTime: ""
  },
  {
    id: "M13",
    group: "H",
    round: 1,
    date: "15/06/2026",
    timestamp: 1781539200000,
    time: "23:00",
    team1Id: "ESP",
    team2Id: "CPV",
    score1: null,
    score2: null,
    yc1: 0,
    rc1: 0,
    yc2: 0,
    rc2: 0,
    status: "Chưa đấu",
    scorers1: [],
    scorers2: [],
    matchTime: ""
  },
  {
    id: "M14",
    group: "G",
    round: 1,
    date: "16/06/2026",
    timestamp: 1781550000000,
    time: "02:00",
    team1Id: "BEL",
    team2Id: "EGY",
    score1: null,
    score2: null,
    yc1: 0,
    rc1: 0,
    yc2: 0,
    rc2: 0,
    status: "Chưa đấu",
    scorers1: [],
    scorers2: [],
    matchTime: ""
  },
  {
    id: "M15",
    group: "H",
    round: 1,
    date: "16/06/2026",
    timestamp: 1781560800000,
    time: "05:00",
    team1Id: "KSA",
    team2Id: "URU",
    score1: null,
    score2: null,
    yc1: 0,
    rc1: 0,
    yc2: 0,
    rc2: 0,
    status: "Chưa đấu",
    scorers1: [],
    scorers2: [],
    matchTime: ""
  },
  {
    id: "M16",
    group: "G",
    round: 1,
    date: "16/06/2026",
    timestamp: 1781571600000,
    time: "08:00",
    team1Id: "IRN",
    team2Id: "NZL",
    score1: null,
    score2: null,
    yc1: 0,
    rc1: 0,
    yc2: 0,
    rc2: 0,
    status: "Chưa đấu",
    scorers1: [],
    scorers2: [],
    matchTime: ""
  },
  {
    id: "M17",
    group: "I",
    round: 1,
    date: "17/06/2026",
    timestamp: 1781636400000,
    time: "02:00",
    team1Id: "FRA",
    team2Id: "SEN",
    score1: null,
    score2: null,
    yc1: 0,
    rc1: 0,
    yc2: 0,
    rc2: 0,
    status: "Chưa đấu",
    scorers1: [],
    scorers2: [],
    matchTime: ""
  },
  {
    id: "M18",
    group: "I",
    round: 1,
    date: "17/06/2026",
    timestamp: 1781647200000,
    time: "05:00",
    team1Id: "IRQ",
    team2Id: "NOR",
    score1: null,
    score2: null,
    yc1: 0,
    rc1: 0,
    yc2: 0,
    rc2: 0,
    status: "Chưa đấu",
    scorers1: [],
    scorers2: [],
    matchTime: ""
  },
  {
    id: "M19",
    group: "J",
    round: 1,
    date: "17/06/2026",
    timestamp: 1781658000000,
    time: "08:00",
    team1Id: "ARG",
    team2Id: "ALG",
    score1: null,
    score2: null,
    yc1: 0,
    rc1: 0,
    yc2: 0,
    rc2: 0,
    status: "Chưa đấu",
    scorers1: [],
    scorers2: [],
    matchTime: ""
  },
  {
    id: "M20",
    group: "J",
    round: 1,
    date: "17/06/2026",
    timestamp: 1781668800000,
    time: "11:00",
    team1Id: "AUT",
    team2Id: "JOR",
    score1: null,
    score2: null,
    yc1: 0,
    rc1: 0,
    yc2: 0,
    rc2: 0,
    status: "Chưa đấu",
    scorers1: [],
    scorers2: [],
    matchTime: ""
  },
  {
    id: "M21",
    group: "K",
    round: 1,
    date: "18/06/2026",
    timestamp: 1781715600000,
    time: "00:00",
    team1Id: "POR",
    team2Id: "COD",
    score1: null,
    score2: null,
    yc1: 0,
    rc1: 0,
    yc2: 0,
    rc2: 0,
    status: "Chưa đấu",
    scorers1: [],
    scorers2: [],
    matchTime: ""
  },
  {
    id: "M22",
    group: "L",
    round: 1,
    date: "18/06/2026",
    timestamp: 1781726400000,
    time: "03:00",
    team1Id: "ENG",
    team2Id: "CRO",
    score1: null,
    score2: null,
    yc1: 0,
    rc1: 0,
    yc2: 0,
    rc2: 0,
    status: "Chưa đấu",
    scorers1: [],
    scorers2: [],
    matchTime: ""
  },
  {
    id: "M23",
    group: "L",
    round: 1,
    date: "18/06/2026",
    timestamp: 1781737200000,
    time: "06:00",
    team1Id: "GHA",
    team2Id: "PAN",
    score1: null,
    score2: null,
    yc1: 0,
    rc1: 0,
    yc2: 0,
    rc2: 0,
    status: "Chưa đấu",
    scorers1: [],
    scorers2: [],
    matchTime: ""
  },
  {
    id: "M24",
    group: "K",
    round: 1,
    date: "18/06/2026",
    timestamp: 1781748000000,
    time: "09:00",
    team1Id: "UZB",
    team2Id: "COL",
    score1: null,
    score2: null,
    yc1: 0,
    rc1: 0,
    yc2: 0,
    rc2: 0,
    status: "Chưa đấu",
    scorers1: [],
    scorers2: [],
    matchTime: ""
  },
  {
    id: "M25",
    group: "A",
    round: 2,
    date: "18/06/2026",
    timestamp: 1781798400000,
    time: "23:00",
    team1Id: "CZE",
    team2Id: "RSA",
    score1: null,
    score2: null,
    yc1: 0,
    rc1: 0,
    yc2: 0,
    rc2: 0,
    status: "Chưa đấu",
    scorers1: [],
    scorers2: [],
    matchTime: ""
  },
  {
    id: "M26",
    group: "B",
    round: 2,
    date: "19/06/2026",
    timestamp: 1781809200000,
    time: "02:00",
    team1Id: "SUI",
    team2Id: "BIH",
    score1: null,
    score2: null,
    yc1: 0,
    rc1: 0,
    yc2: 0,
    rc2: 0,
    status: "Chưa đấu",
    scorers1: [],
    scorers2: [],
    matchTime: ""
  },
  {
    id: "M27",
    group: "B",
    round: 2,
    date: "19/06/2026",
    timestamp: 1781820000000,
    time: "05:00",
    team1Id: "CAN",
    team2Id: "QAT",
    score1: null,
    score2: null,
    yc1: 0,
    rc1: 0,
    yc2: 0,
    rc2: 0,
    status: "Chưa đấu",
    scorers1: [],
    scorers2: [],
    matchTime: ""
  },
  {
    id: "M28",
    group: "A",
    round: 2,
    date: "19/06/2026",
    timestamp: 1781830800000,
    time: "08:00",
    team1Id: "MEX",
    team2Id: "KOR",
    score1: null,
    score2: null,
    yc1: 0,
    rc1: 0,
    yc2: 0,
    rc2: 0,
    status: "Chưa đấu",
    scorers1: [],
    scorers2: [],
    matchTime: ""
  },
  {
    id: "M29",
    group: "D",
    round: 2,
    date: "20/06/2026",
    timestamp: 1781895600000,
    time: "02:00",
    team1Id: "USA",
    team2Id: "AUS",
    score1: null,
    score2: null,
    yc1: 0,
    rc1: 0,
    yc2: 0,
    rc2: 0,
    status: "Chưa đấu",
    scorers1: [],
    scorers2: [],
    matchTime: ""
  },
  {
    id: "M30",
    group: "C",
    round: 2,
    date: "20/06/2026",
    timestamp: 1781906400000,
    time: "05:00",
    team1Id: "SCO",
    team2Id: "MAR",
    score1: null,
    score2: null,
    yc1: 0,
    rc1: 0,
    yc2: 0,
    rc2: 0,
    status: "Chưa đấu",
    scorers1: [],
    scorers2: [],
    matchTime: ""
  },
  {
    id: "M31",
    group: "C",
    round: 2,
    date: "20/06/2026",
    timestamp: 1781915400000,
    time: "07:30",
    team1Id: "BRA",
    team2Id: "HAI",
    score1: null,
    score2: null,
    yc1: 0,
    rc1: 0,
    yc2: 0,
    rc2: 0,
    status: "Chưa đấu",
    scorers1: [],
    scorers2: [],
    matchTime: ""
  },
  {
    id: "M32",
    group: "D",
    round: 2,
    date: "20/06/2026",
    timestamp: 1781924400000,
    time: "10:00",
    team1Id: "TUR",
    team2Id: "PAR",
    score1: null,
    score2: null,
    yc1: 0,
    rc1: 0,
    yc2: 0,
    rc2: 0,
    status: "Chưa đấu",
    scorers1: [],
    scorers2: [],
    matchTime: ""
  },
  {
    id: "M33",
    group: "F",
    round: 2,
    date: "21/06/2026",
    timestamp: 1781974800000,
    time: "00:00",
    team1Id: "NED",
    team2Id: "SWE",
    score1: null,
    score2: null,
    yc1: 0,
    rc1: 0,
    yc2: 0,
    rc2: 0,
    status: "Chưa đấu",
    scorers1: [],
    scorers2: [],
    matchTime: ""
  },
  {
    id: "M34",
    group: "E",
    round: 2,
    date: "21/06/2026",
    timestamp: 1781985600000,
    time: "03:00",
    team1Id: "GER",
    team2Id: "CIV",
    score1: null,
    score2: null,
    yc1: 0,
    rc1: 0,
    yc2: 0,
    rc2: 0,
    status: "Chưa đấu",
    scorers1: [],
    scorers2: [],
    matchTime: ""
  },
  {
    id: "M35",
    group: "E",
    round: 2,
    date: "21/06/2026",
    timestamp: 1782000000000,
    time: "07:00",
    team1Id: "ECU",
    team2Id: "CUW",
    score1: null,
    score2: null,
    yc1: 0,
    rc1: 0,
    yc2: 0,
    rc2: 0,
    status: "Chưa đấu",
    scorers1: [],
    scorers2: [],
    matchTime: ""
  },
  {
    id: "M36",
    group: "F",
    round: 2,
    date: "21/06/2026",
    timestamp: 1782014400000,
    time: "11:00",
    team1Id: "TUN",
    team2Id: "JPN",
    score1: null,
    score2: null,
    yc1: 0,
    rc1: 0,
    yc2: 0,
    rc2: 0,
    status: "Chưa đấu",
    scorers1: [],
    scorers2: [],
    matchTime: ""
  },
  {
    id: "M37",
    group: "H",
    round: 2,
    date: "21/06/2026",
    timestamp: 1782057600000,
    time: "23:00",
    team1Id: "ESP",
    team2Id: "KSA",
    score1: null,
    score2: null,
    yc1: 0,
    rc1: 0,
    yc2: 0,
    rc2: 0,
    status: "Chưa đấu",
    scorers1: [],
    scorers2: [],
    matchTime: ""
  },
  {
    id: "M38",
    group: "G",
    round: 2,
    date: "22/06/2026",
    timestamp: 1782068400000,
    time: "02:00",
    team1Id: "BEL",
    team2Id: "IRN",
    score1: null,
    score2: null,
    yc1: 0,
    rc1: 0,
    yc2: 0,
    rc2: 0,
    status: "Chưa đấu",
    scorers1: [],
    scorers2: [],
    matchTime: ""
  },
  {
    id: "M39",
    group: "H",
    round: 2,
    date: "22/06/2026",
    timestamp: 1782079200000,
    time: "05:00",
    team1Id: "URU",
    team2Id: "CPV",
    score1: null,
    score2: null,
    yc1: 0,
    rc1: 0,
    yc2: 0,
    rc2: 0,
    status: "Chưa đấu",
    scorers1: [],
    scorers2: [],
    matchTime: ""
  },
  {
    id: "M40",
    group: "G",
    round: 2,
    date: "22/06/2026",
    timestamp: 1782090000000,
    time: "08:00",
    team1Id: "NZL",
    team2Id: "EGY",
    score1: null,
    score2: null,
    yc1: 0,
    rc1: 0,
    yc2: 0,
    rc2: 0,
    status: "Chưa đấu",
    scorers1: [],
    scorers2: [],
    matchTime: ""
  },
  {
    id: "M41",
    group: "J",
    round: 2,
    date: "23/06/2026",
    timestamp: 1782147600000,
    time: "00:00",
    team1Id: "ARG",
    team2Id: "AUT",
    score1: null,
    score2: null,
    yc1: 0,
    rc1: 0,
    yc2: 0,
    rc2: 0,
    status: "Chưa đấu",
    scorers1: [],
    scorers2: [],
    matchTime: ""
  },
  {
    id: "M42",
    group: "I",
    round: 2,
    date: "23/06/2026",
    timestamp: 1782162000000,
    time: "04:00",
    team1Id: "FRA",
    team2Id: "IRQ",
    score1: null,
    score2: null,
    yc1: 0,
    rc1: 0,
    yc2: 0,
    rc2: 0,
    status: "Chưa đấu",
    scorers1: [],
    scorers2: [],
    matchTime: ""
  },
  {
    id: "M43",
    group: "I",
    round: 2,
    date: "23/06/2026",
    timestamp: 1782172800000,
    time: "07:00",
    team1Id: "NOR",
    team2Id: "SEN",
    score1: null,
    score2: null,
    yc1: 0,
    rc1: 0,
    yc2: 0,
    rc2: 0,
    status: "Chưa đấu",
    scorers1: [],
    scorers2: [],
    matchTime: ""
  },
  {
    id: "M44",
    group: "J",
    round: 2,
    date: "23/06/2026",
    timestamp: 1782183600000,
    time: "10:00",
    team1Id: "JOR",
    team2Id: "ALG",
    score1: null,
    score2: null,
    yc1: 0,
    rc1: 0,
    yc2: 0,
    rc2: 0,
    status: "Chưa đấu",
    scorers1: [],
    scorers2: [],
    matchTime: ""
  },
  {
    id: "M45",
    group: "K",
    round: 2,
    date: "24/06/2026",
    timestamp: 1782234000000,
    time: "00:00",
    team1Id: "POR",
    team2Id: "UZB",
    score1: null,
    score2: null,
    yc1: 0,
    rc1: 0,
    yc2: 0,
    rc2: 0,
    status: "Chưa đấu",
    scorers1: [],
    scorers2: [],
    matchTime: ""
  },
  {
    id: "M46",
    group: "L",
    round: 2,
    date: "24/06/2026",
    timestamp: 1782244800000,
    time: "03:00",
    team1Id: "ENG",
    team2Id: "GHA",
    score1: null,
    score2: null,
    yc1: 0,
    rc1: 0,
    yc2: 0,
    rc2: 0,
    status: "Chưa đấu",
    scorers1: [],
    scorers2: [],
    matchTime: ""
  },
  {
    id: "M47",
    group: "L",
    round: 2,
    date: "24/06/2026",
    timestamp: 1782255600000,
    time: "06:00",
    team1Id: "PAN",
    team2Id: "CRO",
    score1: null,
    score2: null,
    yc1: 0,
    rc1: 0,
    yc2: 0,
    rc2: 0,
    status: "Chưa đấu",
    scorers1: [],
    scorers2: [],
    matchTime: ""
  },
  {
    id: "M48",
    group: "K",
    round: 2,
    date: "24/06/2026",
    timestamp: 1782266400000,
    time: "09:00",
    team1Id: "COL",
    team2Id: "COD",
    score1: null,
    score2: null,
    yc1: 0,
    rc1: 0,
    yc2: 0,
    rc2: 0,
    status: "Chưa đấu",
    scorers1: [],
    scorers2: [],
    matchTime: ""
  },
  {
    id: "M49",
    group: "B",
    round: 3,
    date: "25/06/2026",
    timestamp: 1782327600000,
    time: "02:00",
    team1Id: "BIH",
    team2Id: "QAT",
    score1: null,
    score2: null,
    yc1: 0,
    rc1: 0,
    yc2: 0,
    rc2: 0,
    status: "Chưa đấu",
    scorers1: [],
    scorers2: [],
    matchTime: ""
  },
  {
    id: "M50",
    group: "B",
    round: 3,
    date: "25/06/2026",
    timestamp: 1782327600000,
    time: "02:00",
    team1Id: "SUI",
    team2Id: "CAN",
    score1: null,
    score2: null,
    yc1: 0,
    rc1: 0,
    yc2: 0,
    rc2: 0,
    status: "Chưa đấu",
    scorers1: [],
    scorers2: [],
    matchTime: ""
  },
  {
    id: "M51",
    group: "C",
    round: 3,
    date: "25/06/2026",
    timestamp: 1782338400000,
    time: "05:00",
    team1Id: "MAR",
    team2Id: "HAI",
    score1: null,
    score2: null,
    yc1: 0,
    rc1: 0,
    yc2: 0,
    rc2: 0,
    status: "Chưa đấu",
    scorers1: [],
    scorers2: [],
    matchTime: ""
  },
  {
    id: "M52",
    group: "C",
    round: 3,
    date: "25/06/2026",
    timestamp: 1782338400000,
    time: "05:00",
    team1Id: "SCO",
    team2Id: "BRA",
    score1: null,
    score2: null,
    yc1: 0,
    rc1: 0,
    yc2: 0,
    rc2: 0,
    status: "Chưa đấu",
    scorers1: [],
    scorers2: [],
    matchTime: ""
  },
  {
    id: "M53",
    group: "A",
    round: 3,
    date: "25/06/2026",
    timestamp: 1782349200000,
    time: "08:00",
    team1Id: "CZE",
    team2Id: "MEX",
    score1: null,
    score2: null,
    yc1: 0,
    rc1: 0,
    yc2: 0,
    rc2: 0,
    status: "Chưa đấu",
    scorers1: [],
    scorers2: [],
    matchTime: ""
  },
  {
    id: "M54",
    group: "A",
    round: 3,
    date: "25/06/2026",
    timestamp: 1782349200000,
    time: "08:00",
    team1Id: "RSA",
    team2Id: "KOR",
    score1: null,
    score2: null,
    yc1: 0,
    rc1: 0,
    yc2: 0,
    rc2: 0,
    status: "Chưa đấu",
    scorers1: [],
    scorers2: [],
    matchTime: ""
  },
  {
    id: "M55",
    group: "E",
    round: 3,
    date: "26/06/2026",
    timestamp: 1782417600000,
    time: "03:00",
    team1Id: "CUW",
    team2Id: "CIV",
    score1: null,
    score2: null,
    yc1: 0,
    rc1: 0,
    yc2: 0,
    rc2: 0,
    status: "Chưa đấu",
    scorers1: [],
    scorers2: [],
    matchTime: ""
  },
  {
    id: "M56",
    group: "E",
    round: 3,
    date: "26/06/2026",
    timestamp: 1782417600000,
    time: "03:00",
    team1Id: "ECU",
    team2Id: "GER",
    score1: null,
    score2: null,
    yc1: 0,
    rc1: 0,
    yc2: 0,
    rc2: 0,
    status: "Chưa đấu",
    scorers1: [],
    scorers2: [],
    matchTime: ""
  },
  {
    id: "M57",
    group: "F",
    round: 3,
    date: "26/06/2026",
    timestamp: 1782428400000,
    time: "06:00",
    team1Id: "JPN",
    team2Id: "SWE",
    score1: null,
    score2: null,
    yc1: 0,
    rc1: 0,
    yc2: 0,
    rc2: 0,
    status: "Chưa đấu",
    scorers1: [],
    scorers2: [],
    matchTime: ""
  },
  {
    id: "M58",
    group: "F",
    round: 3,
    date: "26/06/2026",
    timestamp: 1782428400000,
    time: "06:00",
    team1Id: "TUN",
    team2Id: "NED",
    score1: null,
    score2: null,
    yc1: 0,
    rc1: 0,
    yc2: 0,
    rc2: 0,
    status: "Chưa đấu",
    scorers1: [],
    scorers2: [],
    matchTime: ""
  },
  {
    id: "M59",
    group: "D",
    round: 3,
    date: "26/06/2026",
    timestamp: 1782439200000,
    time: "09:00",
    team1Id: "PAR",
    team2Id: "AUS",
    score1: null,
    score2: null,
    yc1: 0,
    rc1: 0,
    yc2: 0,
    rc2: 0,
    status: "Chưa đấu",
    scorers1: [],
    scorers2: [],
    matchTime: ""
  },
  {
    id: "M60",
    group: "D",
    round: 3,
    date: "26/06/2026",
    timestamp: 1782439200000,
    time: "09:00",
    team1Id: "TUR",
    team2Id: "USA",
    score1: null,
    score2: null,
    yc1: 0,
    rc1: 0,
    yc2: 0,
    rc2: 0,
    status: "Chưa đấu",
    scorers1: [],
    scorers2: [],
    matchTime: ""
  },
  {
    id: "M61",
    group: "I",
    round: 3,
    date: "27/06/2026",
    timestamp: 1782500400000,
    time: "02:00",
    team1Id: "NOR",
    team2Id: "FRA",
    score1: null,
    score2: null,
    yc1: 0,
    rc1: 0,
    yc2: 0,
    rc2: 0,
    status: "Chưa đấu",
    scorers1: [],
    scorers2: [],
    matchTime: ""
  },
  {
    id: "M62",
    group: "I",
    round: 3,
    date: "27/06/2026",
    timestamp: 1782500400000,
    time: "02:00",
    team1Id: "SEN",
    team2Id: "IRQ",
    score1: null,
    score2: null,
    yc1: 0,
    rc1: 0,
    yc2: 0,
    rc2: 0,
    status: "Chưa đấu",
    scorers1: [],
    scorers2: [],
    matchTime: ""
  },
  {
    id: "M63",
    group: "H",
    round: 3,
    date: "27/06/2026",
    timestamp: 1782518400000,
    time: "07:00",
    team1Id: "CPV",
    team2Id: "KSA",
    score1: null,
    score2: null,
    yc1: 0,
    rc1: 0,
    yc2: 0,
    rc2: 0,
    status: "Chưa đấu",
    scorers1: [],
    scorers2: [],
    matchTime: ""
  },
  {
    id: "M64",
    group: "H",
    round: 3,
    date: "27/06/2026",
    timestamp: 1782518400000,
    time: "07:00",
    team1Id: "URU",
    team2Id: "ESP",
    score1: null,
    score2: null,
    yc1: 0,
    rc1: 0,
    yc2: 0,
    rc2: 0,
    status: "Chưa đấu",
    scorers1: [],
    scorers2: [],
    matchTime: ""
  },
  {
    id: "M65",
    group: "G",
    round: 3,
    date: "27/06/2026",
    timestamp: 1782529200000,
    time: "10:00",
    team1Id: "EGY",
    team2Id: "IRN",
    score1: null,
    score2: null,
    yc1: 0,
    rc1: 0,
    yc2: 0,
    rc2: 0,
    status: "Chưa đấu",
    scorers1: [],
    scorers2: [],
    matchTime: ""
  },
  {
    id: "M66",
    group: "G",
    round: 3,
    date: "27/06/2026",
    timestamp: 1782529200000,
    time: "10:00",
    team1Id: "NZL",
    team2Id: "BEL",
    score1: null,
    score2: null,
    yc1: 0,
    rc1: 0,
    yc2: 0,
    rc2: 0,
    status: "Chưa đấu",
    scorers1: [],
    scorers2: [],
    matchTime: ""
  },
  {
    id: "M67",
    group: "L",
    round: 3,
    date: "28/06/2026",
    timestamp: 1782594000000,
    time: "04:00",
    team1Id: "CRO",
    team2Id: "GHA",
    score1: null,
    score2: null,
    yc1: 0,
    rc1: 0,
    yc2: 0,
    rc2: 0,
    status: "Chưa đấu",
    scorers1: [],
    scorers2: [],
    matchTime: ""
  },
  {
    id: "M68",
    group: "L",
    round: 3,
    date: "28/06/2026",
    timestamp: 1782594000000,
    time: "04:00",
    team1Id: "PAN",
    team2Id: "ENG",
    score1: null,
    score2: null,
    yc1: 0,
    rc1: 0,
    yc2: 0,
    rc2: 0,
    status: "Chưa đấu",
    scorers1: [],
    scorers2: [],
    matchTime: ""
  },
  {
    id: "M69",
    group: "K",
    round: 3,
    date: "28/06/2026",
    timestamp: 1782603000000,
    time: "06:30",
    team1Id: "COL",
    team2Id: "POR",
    score1: null,
    score2: null,
    yc1: 0,
    rc1: 0,
    yc2: 0,
    rc2: 0,
    status: "Chưa đấu",
    scorers1: [],
    scorers2: [],
    matchTime: ""
  },
  {
    id: "M70",
    group: "K",
    round: 3,
    date: "28/06/2026",
    timestamp: 1782603000000,
    time: "06:30",
    team1Id: "COD",
    team2Id: "UZB",
    score1: null,
    score2: null,
    yc1: 0,
    rc1: 0,
    yc2: 0,
    rc2: 0,
    status: "Chưa đấu",
    scorers1: [],
    scorers2: [],
    matchTime: ""
  },
  {
    id: "M71",
    group: "J",
    round: 3,
    date: "28/06/2026",
    timestamp: 1782612000000,
    time: "09:00",
    team1Id: "ALG",
    team2Id: "AUT",
    score1: null,
    score2: null,
    yc1: 0,
    rc1: 0,
    yc2: 0,
    rc2: 0,
    status: "Chưa đấu",
    scorers1: [],
    scorers2: [],
    matchTime: ""
  },
  {
    id: "M72",
    group: "J",
    round: 3,
    date: "28/06/2026",
    timestamp: 1782612000000,
    time: "09:00",
    team1Id: "JOR",
    team2Id: "ARG",
    score1: null,
    score2: null,
    yc1: 0,
    rc1: 0,
    yc2: 0,
    rc2: 0,
    status: "Chưa đấu",
    scorers1: [],
    scorers2: [],
    matchTime: ""
  },
];

// HÃ m bá»• trá»£ tÃ¬m kiáº¿m thÃ´ng tin chi tiáº¿t cá»§a Ä‘á»™i bÃ³ng theo ID
function findTeamById(teamId) {
  for (const groupLetter of Object.keys(WORLD_CUP_DATA.groups)) {
    const team = WORLD_CUP_DATA.groups[groupLetter].find(t => t.id === teamId);
    if (team) return team;
  }
  return null;
}

// Khá»Ÿi táº¡o DEFAULT_MATCHES vá»›i Ä‘áº§y Ä‘á»§ thÃ´ng tin tÃªn tiáº¿ng Viá»‡t, cá» vÃ  cá» hiá»‡u
const DEFAULT_MATCHES = OFFICIAL_MATCHES_RAW.map(match => {
  const t1 = findTeamById(match.team1Id);
  const t2 = findTeamById(match.team2Id);
  return {
    ...match,
    team1: t1 ? t1.name : "",
    team1FlagCode: t1 ? t1.flagCode : "",
    team1Flag: t1 ? t1.flag : "",
    team2: t2 ? t2.name : "",
    team2FlagCode: t2 ? t2.flagCode : "",
    team2Flag: t2 ? t2.flag : "",
    matchTime: match.matchTime || ""
  };
});


// Dữ liệu thống kê cầu thủ World Cup 2026 (Mặc định khởi tạo 0, tự động tích lũy từ kết quả đấu)
const PLAYER_STATS_DATA = [
  { name: "Kylian Mbappé", team: "Pháp", flagCode: "fr", goals: 0, assists: 0, xg: 0.0, keyPasses: 0 },
  { name: "Harry Kane", team: "Anh", flagCode: "gb-eng", goals: 0, assists: 0, xg: 0.0, keyPasses: 0 },
  { name: "Vinícius Júnior", team: "Brazil", flagCode: "br", goals: 0, assists: 0, xg: 0.0, keyPasses: 0 },
  { name: "Jude Bellingham", team: "Anh", flagCode: "gb-eng", goals: 0, assists: 0, xg: 0.0, keyPasses: 0 },
  { name: "Erling Haaland", team: "Na Uy", flagCode: "no", goals: 0, assists: 0, xg: 0.0, keyPasses: 0 },
  { name: "Son Heung-min", team: "Hàn Quốc", flagCode: "kr", goals: 0, assists: 0, xg: 0.0, keyPasses: 0 },
  { name: "Jamal Musiala", team: "Đức", flagCode: "de", goals: 0, assists: 0, xg: 0.0, keyPasses: 0 },
  { name: "Kevin De Bruyne", team: "Bỉ", flagCode: "be", goals: 0, assists: 0, xg: 0.0, keyPasses: 0 },
  { name: "Bruno Fernandes", team: "Bồ Đào Nha", flagCode: "pt", goals: 0, assists: 0, xg: 0.0, keyPasses: 0 },
  { name: "Lionel Messi", team: "Argentina", flagCode: "ar", goals: 0, assists: 0, xg: 0.0, keyPasses: 0 }
];

// Danh sách các cầu thủ tiêu biểu của 48 quốc gia tham dự World Cup 2026
const TEAM_PLAYERS = {
  "Mexico": [
    { name: "Santiago Giménez", flagCode: "mx" },
    { name: "Hirving Lozano", flagCode: "mx" },
    { name: "Edson Álvarez", flagCode: "mx" }
  ],
  "Hàn Quốc": [
    { name: "Son Heung-min", flagCode: "kr" },
    { name: "Hwang Hee-chan", flagCode: "kr" },
    { name: "Lee Kang-in", flagCode: "kr" }
  ],
  "Nam Phi": [
    { name: "Percy Tau", flagCode: "za" },
    { name: "Themba Zwane", flagCode: "za" }
  ],
  "Cộng hòa Séc": [
    { name: "Patrik Schick", flagCode: "cz" },
    { name: "Tomáš Souček", flagCode: "cz" }
  ],
  "Canada": [
    { name: "Jonathan David", flagCode: "ca" },
    { name: "Alphonso Davies", flagCode: "ca" },
    { name: "Cyle Larin", flagCode: "ca" }
  ],
  "Thụy Sĩ": [
    { name: "Breel Embolo", flagCode: "ch" },
    { name: "Xherdan Shaqiri", flagCode: "ch" },
    { name: "Granit Xhaka", flagCode: "ch" }
  ],
  "Qatar": [
    { name: "Akram Afif", flagCode: "qa" },
    { name: "Almoez Ali", flagCode: "qa" }
  ],
  "Bosnia-Herzegovina": [
    { name: "Edin Džeko", flagCode: "ba" },
    { name: "Miralem Pjanić", flagCode: "ba" }
  ],
  "Brazil": [
    { name: "Vinícius Júnior", flagCode: "br" },
    { name: "Rodrygo", flagCode: "br" },
    { name: "Neymar Jr", flagCode: "br" }
  ],
  "Morocco": [
    { name: "Youssef En-Nesyri", flagCode: "ma" },
    { name: "Hakim Ziyech", flagCode: "ma" },
    { name: "Achraf Hakimi", flagCode: "ma" }
  ],
  "Scotland": [
    { name: "Scott McTominay", flagCode: "gb-sct" },
    { name: "John McGinn", flagCode: "gb-sct" }
  ],
  "Haiti": [
    { name: "Frantzdy Pierrot", flagCode: "ht" },
    { name: "Duckens Nazon", flagCode: "ht" }
  ],
  "Mỹ": [
    { name: "Christian Pulisic", flagCode: "us" },
    { name: "Folarin Balogun", flagCode: "us" },
    { name: "Timothy Weah", flagCode: "us" }
  ],
  "Paraguay": [
    { name: "Miguel Almirón", flagCode: "py" },
    { name: "Julio Enciso", flagCode: "py" }
  ],
  "Úc": [
    { name: "Craig Goodwin", flagCode: "au" },
    { name: "Mitchell Duke", flagCode: "au" }
  ],
  "Thổ Nhĩ Kỳ": [
    { name: "Arda Güler", flagCode: "tr" },
    { name: "Hakan Çalhanoğlu", flagCode: "tr" },
    { name: "Cenk Tosun", flagCode: "tr" }
  ],
  "Đức": [
    { name: "Jamal Musiala", flagCode: "de" },
    { name: "Florian Wirtz", flagCode: "de" },
    { name: "Niclas Füllkrug", flagCode: "de" }
  ],
  "Ecuador": [
    { name: "Enner Valencia", flagCode: "ec" },
    { name: "Kendry Páez", flagCode: "ec" }
  ],
  "Bờ Biển Ngà": [
    { name: "Sébastien Haller", flagCode: "ci" },
    { name: "Simon Adingra", flagCode: "ci" }
  ],
  "Curacao": [
    { name: "Juninho Bacuna", flagCode: "cw" },
    { name: "Rangelo Janga", flagCode: "cw" }
  ],
  "Hà Lan": [
    { name: "Cody Gakpo", flagCode: "nl" },
    { name: "Memphis Depay", flagCode: "nl" },
    { name: "Xavi Simons", flagCode: "nl" }
  ],
  "Nhật Bản": [
    { name: "Kaoru Mitoma", flagCode: "jp" },
    { name: "Takefusa Kubo", flagCode: "jp" },
    { name: "Ayase Ueda", flagCode: "jp" }
  ],
  "Tunisia": [
    { name: "Youssef Msakni", flagCode: "tn" },
    { name: "Montassar Talbi", flagCode: "tn" }
  ],
  "Thụy Điển": [
    { name: "Alexander Isak", flagCode: "se" },
    { name: "Viktor Gyökeres", flagCode: "se" },
    { name: "Dejan Kulusevski", flagCode: "se" }
  ],
  "Bỉ": [
    { name: "Kevin De Bruyne", flagCode: "be" },
    { name: "Romelu Lukaku", flagCode: "be" },
    { name: "Leandro Trossard", flagCode: "be" }
  ],
  "Iran": [
    { name: "Mehdi Taremi", flagCode: "ir" },
    { name: "Sardar Azmoun", flagCode: "ir" }
  ],
  "Ai Cập": [
    { name: "Mohamed Salah", flagCode: "eg" },
    { name: "Mostafa Mohamed", flagCode: "eg" }
  ],
  "New Zealand": [
    { name: "Chris Wood", flagCode: "nz" },
    { name: "Sarpreet Singh", flagCode: "nz" }
  ],
  "Tây Ban Nha": [
    { name: "Lamine Yamal", flagCode: "es" },
    { name: "Álvaro Morata", flagCode: "es" },
    { name: "Nico Williams", flagCode: "es" }
  ],
  "Uruguay": [
    { name: "Darwin Núñez", flagCode: "uy" },
    { name: "Federico Valverde", flagCode: "uy" },
    { name: "Luis Suárez", flagCode: "uy" }
  ],
  "Saudi Arabia": [
    { name: "Salem Al-Dawsari", flagCode: "sa" },
    { name: "Firas Al-Buraikan", flagCode: "sa" }
  ],
  "Cape Verde": [
    { name: "Ryan Mendes", flagCode: "cv" },
    { name: "Bebé", flagCode: "cv" }
  ],
  "Pháp": [
    { name: "Kylian Mbappé", flagCode: "fr" },
    { name: "Antoine Griezmann", flagCode: "fr" },
    { name: "Olivier Giroud", flagCode: "fr" }
  ],
  "Senegal": [
    { name: "Sadio Mané", flagCode: "sn" },
    { name: "Nicolas Jackson", flagCode: "sn" }
  ],
  "Na Uy": [
    { name: "Erling Haaland", flagCode: "no" },
    { name: "Martin Ødegaard", flagCode: "no" }
  ],
  "Iraq": [
    { name: "Aymen Hussein", flagCode: "iq" },
    { name: "Ali Jasim", flagCode: "iq" }
  ],
  "Argentina": [
    { name: "Lionel Messi", flagCode: "ar" },
    { name: "Lautaro Martínez", flagCode: "ar" },
    { name: "Julián Álvarez", flagCode: "ar" }
  ],
  "Áo": [
    { name: "Michael Gregoritsch", flagCode: "at" },
    { name: "Marcel Sabitzer", flagCode: "at" }
  ],
  "Algeria": [
    { name: "Riyad Mahrez", flagCode: "dz" },
    { name: "Baghdad Bounedjah", flagCode: "dz" }
  ],
  "Jordan": [
    { name: "Musa Al-Taamari", flagCode: "jo" },
    { name: "Yazan Al-Naimat", flagCode: "jo" }
  ],
  "Bồ Đào Nha": [
    { name: "Cristiano Ronaldo", flagCode: "pt" },
    { name: "Bruno Fernandes", flagCode: "pt" },
    { name: "Rafael Leão", flagCode: "pt" }
  ],
  "Colombia": [
    { name: "Luis Díaz", flagCode: "co" },
    { name: "James Rodríguez", flagCode: "co" }
  ],
  "Uzbekistan": [
    { name: "Eldor Shomurodov", flagCode: "uz" },
    { name: "Otabek Shukurov", flagCode: "uz" }
  ],
  "CH Dân Chủ Congo": [
    { name: "Yoane Wissa", flagCode: "cd" },
    { name: "Cédric Bakambu", flagCode: "cd" }
  ],
  "Anh": [
    { name: "Harry Kane", flagCode: "gb-eng" },
    { name: "Jude Bellingham", flagCode: "gb-eng" },
    { name: "Bukayo Saka", flagCode: "gb-eng" }
  ],
  "Croatia": [
    { name: "Andrej Kramarić", flagCode: "hr" },
    { name: "Luka Modrić", flagCode: "hr" }
  ],
  "Panama": [
    { name: "Cecilio Waterman", flagCode: "pa" },
    { name: "Ismael Díaz", flagCode: "pa" }
  ],
  "Ghana": [
    { name: "Inaki Williams", flagCode: "gh" },
    { name: "Mohammed Kudus", flagCode: "gh" }
  ]
};